FROM php:7.3.23-fpm-alpine

# php extensions
RUN apk add --no-cache --virtual dev freetype-dev libjpeg-turbo-dev libpng-dev libzip-dev libxml2-dev \
    && apk add --no-cache freetype libjpeg-turbo libpng libzip libxml2 \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include --with-jpeg-dir=/usr/include \
    && docker-php-ext-install gd soap zip bcmath pdo_mysql \
    && apk del dev

# xdebug
RUN apk add --no-cache --virtual dev $PHPIZE_DEPS \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_autostart=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && apk del dev