FROM php:7.4-fpm-alpine

RUN apk update \
    && apk add --no-cache --virtual dev freetype-dev libjpeg-turbo-dev libpng-dev libzip-dev libxml2-dev \
    && apk add --no-cache freetype libjpeg-turbo libpng libzip libxml2 \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include --with-jpeg-dir=/usr/include \
    && docker-php-ext-install -j$(nproc) zip bcmath soap pdo_mysql opcache \
    && apk del dev
